-- This lua file has been fetched from the bot VICTOR which is the exclusive property of Piracy Lords server.
-- Redistribution of VICTORs files is not allowed AT ALL
-- Join the offical here: https://discord.gg/piracylords

addappid(3049990)
addappid(3486450)
addappid(3498450)
addappid(3498460)
addappid(3498470)
addappid(3498480)
addappid(3498490)
addappid(3526890)
addappid(3529060)
addappid(3049992,0,"c66837576c962858096fcd26377b1784c8096993a5841386af499b42446cd8b0")
addappid(3529070,0,"b026350733364aae827ef7a7c5167c3ee7ee13282002f1996ed6bd765db6bc23")
setManifestid(3049992,"449785237876940508")
setManifestid(3529070,"4349303088942931691")


-- Generated By [Manilua Creator v3.2.2.4] ~ Game: Phantom Brave: The Lost Hero