-- This lua file has been fetched from the bot VICTOR which is the exclusive property of Piracy Lords server.
-- Redistribution of VICTORs files is not allowed AT ALL
-- Join the offical here: https://discord.gg/piracylords

addappid(3077390)
addappid(3374650)
addappid(3374660)
addappid(3077391,0,"ee460f4a0c4fdcfbdd31a8e7d084bd72dab87c59bde5939c020cc9c2da9ba48b")
setManifestid(3077391,"2178783896599605259")


-- Generated By [Manilua Creator v3.2.2.4] ~ Game: MotoGP™25